name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build and push image
    uses: bl4ko/shared-actions/.github/workflows/build_image.yml@c8e4ab561a021406c319ecc53e4f5f3b801557a7 # main
    with:
      tags: "ghcr.io/bl4ko/kubescape-exporter:${{ github.ref_name }},ghcr.io/bl4ko/kubescape-exporter:latest"
      platform: "linux/amd64"
      runs-on: "ubuntu-latest"
