name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build and push image
    uses: bl4ko/shared-actions/.github/workflows/build_image.yml@431af233f489ca5b34f76a9f34ee30c688ff93d5 # main
    with:
      tags: "ghcr.io/bl4ko/kubescape-exporter:${{ github.ref_name }},ghcr.io/bl4ko/kubescape-exporter:latest"
      platform: "linux/amd64"
      runs-on: "ubuntu-latest"
